import React, { useState, useEffect } from 'react';
import { useAuth } from '../contexts/AuthContext';
import API_URL from '../config/api';

interface IClip {
  _id: string;
  videoUrl: string;
  generatedBy: {
    userId: string;
    username: string;
  };
  createdAt: string;
}

const Clips: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'all' | 'my'>('all');
  const [clips, setClips] = useState<IClip[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { token } = useAuth();

  useEffect(() => {
    const fetchClips = async () => {
      setIsLoading(true);
      const endpoint = activeTab === 'all' ? '/clips' : '/clips/my-clips';
      const headers: HeadersInit = {
        'Content-Type': 'application/json',
      };

      if (activeTab === 'my' && token) {
        headers['Authorization'] = `Bearer ${token}`;
      }

      try {
        const res = await fetch(`${API_URL}${endpoint}`, { headers });
        if (!res.ok) {
          throw new Error('Failed to fetch clips');
        }
        const data = await res.json();
        setClips(data);
      } catch (error) {
        console.error("Error fetching clips:", error);
        setClips([]); // Clear clips on error
      } finally {
        setIsLoading(false);
      }
    };

    fetchClips();
  }, [activeTab, token]);

  return (
    <div className="min-h-screen w-full p-4 sm:p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-5xl font-bold text-white text-center mb-8">Generated Clips</h1>

        {/* Tabs */}
        <div className="flex justify-center border-b border-white/20 mb-8">
          <button
            onClick={() => setActiveTab('all')}
            className={`px-6 py-3 text-lg font-medium transition-colors ${
              activeTab === 'all'
                ? 'text-neon-purple border-b-2 border-neon-purple'
                : 'text-gray-400 hover:text-white'
            }`}
          >
            All Clips
          </button>
          <button
            onClick={() => setActiveTab('my')}
            className={`px-6 py-3 text-lg font-medium transition-colors ${
              activeTab === 'my'
                ? 'text-neon-purple border-b-2 border-neon-purple'
                : 'text-gray-400 hover:text-white'
            }`}
          >
            My Clips
          </button>
        </div>

        {/* Clips Grid */}
        {isLoading ? (
          <div className="text-center text-white text-xl">Loading clips...</div>
        ) : clips.length === 0 ? (
          <div className="text-center text-gray-400 text-xl">No clips found.</div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {clips.map((clip) => (
              <div key={clip._id} className="bg-black/30 backdrop-blur-lg border border-white/10 rounded-2xl overflow-hidden shadow-lg">
                <video controls className="w-full aspect-[9/16] object-cover bg-black">
                  <source src={clip.videoUrl} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
                <div className="p-4">
                  <p className="text-sm text-gray-300">Generated by <span className="font-bold text-white">{clip.generatedBy.username}</span></p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Clips;
